/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/schools/{school_id}": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Read School */
        get: operations["read_school_schools__school_id__get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/schools/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Read Schools */
        get: operations["read_schools_schools__get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/school_types/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Read School Types
         * @description Fetch all available school types or just one type if type name is provided.
         */
        get: operations["read_school_types_school_types__get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/school_types/{school_type_id}": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Read School Type By Id */
        get: operations["read_school_type_by_id_school_types__school_type_id__get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Read Root */
        get: operations["read_root__get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/users": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Read Users */
        get: operations["read_users_users_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][]
        }
        /** StatusPublicznoprawnyPublic */
        StatusPublicznoprawnyPublic: {
            /** Nazwa */
            nazwa: string
            /** Id */
            id: number
        }
        /** SzkolaPublic */
        SzkolaPublic: {
            /** Numer Rspo */
            numer_rspo: number
            /** Nazwa */
            nazwa: string
            /** Nip */
            nip?: string | null
            /** Regon */
            regon: string
            /** Liczba Uczniow */
            liczba_uczniow?: number | null
            /** Dyrektor Imie */
            dyrektor_imie?: string | null
            /** Dyrektor Nazwisko */
            dyrektor_nazwisko?: string | null
            /** Kod Pocztowy */
            kod_pocztowy: string
            /** Numer Budynku */
            numer_budynku?: string | null
            /** Numer Lokalu */
            numer_lokalu?: string | null
            /** Telefon */
            telefon?: string | null
            /** Email */
            email?: string | null
            /** Strona Internetowa */
            strona_internetowa?: string | null
            /** Geolokalizacja Latitude */
            geolokalizacja_latitude: number
            /** Geolokalizacja Longitude */
            geolokalizacja_longitude: number
            /**
             * Score
             * @default 0
             */
            score: number
            /** Typ Id */
            typ_id?: number | null
            /** Status Publicznoprawny Id */
            status_publicznoprawny_id?: number | null
            /** Kategoria Uczniow Id */
            kategoria_uczniow_id?: number | null
            /** Miejscowosc Id */
            miejscowosc_id?: number | null
            /** Ulica Id */
            ulica_id?: number | null
            /** Id */
            id: number
        }
        /** SzkolaPublicShort */
        SzkolaPublicShort: {
            /** Numer Rspo */
            numer_rspo: number
            /** Nazwa */
            nazwa: string
            /** Id */
            id: number
            /** Geolokalizacja Latitude */
            geolokalizacja_latitude: number
            /** Geolokalizacja Longitude */
            geolokalizacja_longitude: number
            /** Score */
            score: number
            typ: components["schemas"]["TypSzkolyPublic"]
            status_publicznoprawny: components["schemas"]["StatusPublicznoprawnyPublic"]
        }
        /** TypSzkolyPublic */
        TypSzkolyPublic: {
            /** Nazwa */
            nazwa: string
            /** Id */
            id: number
        }
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[]
            /** Message */
            msg: string
            /** Error Type */
            type: string
        }
    }
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    read_school_schools__school_id__get: {
        parameters: {
            query?: never
            header?: never
            path: {
                school_id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["SzkolaPublic"]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    read_schools_schools__get: {
        parameters: {
            query: {
                north: number
                south: number
                west: number
                east: number
                type?: number | null
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["SzkolaPublicShort"][]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    read_school_types_school_types__get: {
        parameters: {
            query?: {
                name?: string | null
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json":
                        | components["schemas"]["TypSzkolyPublic"][]
                        | components["schemas"]["TypSzkolyPublic"]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    read_school_type_by_id_school_types__school_type_id__get: {
        parameters: {
            query?: never
            header?: never
            path: {
                school_type_id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["TypSzkolyPublic"]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    read_root__get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": unknown
                }
            }
        }
    }
    read_users_users_get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": unknown
                }
            }
        }
    }
}
